name:  ${{values.app_name}}-cicd

on:
  push:
    paths:
      - "src/**"
    branches: [ "main", "master" ]
      

jobs:
  ci:
    
    runs-on: ubuntu-latest

    steps:
      - name: shorten commit id
        shell: bash
        run: |
         echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
         echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}/${{values.app_name}}:${{ '${{ env.COMMIT_ID}}' }}
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID}}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          curl -sL https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -o /tmp/yq
          chmod +x /tmp/yq
          /tmp/yq -i '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/${{values.app_name}}/values-${{values.app.env}}.yaml
 
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'update values.yaml with commit{{needs.ci.outputs.commit_id}}'
            

      - name: Install argocd
        shell: bash
        run: | 
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
         argocd login argocd-server.argocd \
         --insecure \
         --grpc-web \
         --username ${{ '${{ secrets.Argocd_USERNAME }}' }} \
         --password ${{ '${{ secrets.Argocd_password }}' }} 
         argocd app sync  ${{values.app_name}}